image: node:latest

stages:
  - build
  - test
  - deploy
  - release


build:
  stage: build
  script:
    - npm i
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

tests:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - npm run test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml

review_app:
  stage: deploy
  only:
    - merge_requests
  trigger:
    include: "pipelines/review_app.yml"
  
