image: ubuntu:latest

stages:
  - build
  - test
  - deploy
  - release
  
review_app:
  stage: deploy
  only:
    - branches
  except:
    - /^develop-.*$/
    - /^main-.*$/
  trigger:
    include: "pipelines/review_app.yml"



  
