image: node:latest

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - npm i
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

tests:
  stage: test
  script:
    - "npm run test"
  artifacts:
    paths:
      - "coverage/"
    reports:
      coverage_report:
        coverage_format: "cobertura"
        path: "coverage/cobertura-coverage.xml"
      junit: "coverage/junit.xml"
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

review_app:
  stage: deploy
  only:
    - merge_requests
  trigger:
    include: "pipelines/review_app.yml"
  when: on_success

release:
  stage: release
  only:
    - main
  trigger:
    include: "pipelines/release.yml"
  when: on_success